<?php
/**
 * Created by PhpStorm.
 * User: xiaohongyang
 * Date: 2016/11/25
 * Time: 23:25
 */

namespace app\controllers;


use yii\base\Event;
use yii\helpers\Url;
use yii\web\Controller;
use yii\helpers\Json;
use yii\web\Response;

class BaseController extends Controller
{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        \Yii::$app->language = 'zh-CN';


    }


    public function renderJson($status=null, $message=null, $data=array(), $url = null, $break=false)
    {
        \Yii::$app->response->format = Response::FORMAT_JSON;

        if ((!is_null($status) && $message) || (is_array($data) && count($data) )) {
            \Yii::$app->response->data = [
                'status' => $status,
                'message' => $message,
                'data' => $data,
                'url' => $url
            ];
        } else {
            \Yii::$app->response->data = $status;
        }

        if($break){

            echo json_encode(\Yii::$app->response->data, JSON_UNESCAPED_UNICODE);
            exit;
        }

    }

    public function checkLogin($isJson=false){
        if(\Yii::$app->user->isGuest && $isJson) {
            return $this->renderJson(STATUS_NOT_LOGIN, "您尚未登录,请先登录", [], null, true);
        } else if(\Yii::$app->user->isGuest) {
            $this->redirect(Url::to(['/site/login']));
        }
    }


}