<?php

namespace app\controllers;

use app\common\components\helpers\MapHelper;
use app\common\components\helpers\ToolsHelper;
use app\common\components\helpers\WeChatHelper;
use app\models\RegisterModel;
use app\models\RegisterUserInfoModel;
use app\models\TeamModel;
use app\models\TeamUserModel;
use app\models\UserIdentity;
use app\models\UserModel;
use app\models\WeChatModel;
use linslin\yii2\curl\Curl;
use Yii;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use yii\web\Cookie;

class SiteController extends BaseController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->layout = false;
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
//                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $teamModel = null;
        if(!Yii::$app->user->isGuest) {

            $userId = Yii::$app->user->identity->getId();

            $teamIds = TeamUserModel::find()->where(['user_id' => $userId])->select('team_id')->one() ;
            $teamModel = TeamModel::findOne([  'team_id' => $teamIds]);
        }

        return $this->render('index', [
            'teamModel' => $teamModel
        ]);
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {

        if(ToolsHelper::isWeChatBrowser()) {

            $wxOpenid = Yii::$app->request->get('wxOpenid');
            if(!$wxOpenid){
                $cookies = Yii::$app->request->cookies;
                if(!$cookies->has('wxOpenid')){
                    $url = "https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx2887eeeac1e7d898&redirect_uri=" . urlencode("http://gx.xjc1.com/wx/oauth2") . "&response_type=code&scope=snsapi_base&state=1#wechat_redirect";
                    header("Location:$url");
                    return false;
                } else {
                    /*var_dump($cookies->get('wxOpenid'));
                    echo '<br/>';
                    var_dump($cookies->get('wxOpenid')->value);*/
                }
            }else{
                //cookie('wxOpenid',$wxOpenid,36000000000);
                $cookies = Yii::$app->response->cookies;
                $cookies->add(new Cookie([
                    'name' => wxOpenid,
                    'value' => $wxOpenid,
                    'expire' => 36000000000
                ]));
            }
        }

        if (!Yii::$app->user->isGuest) {

            $user = UserIdentity::findOne(['id' => Yii::$app->user->id]);
            $userInfo = $user->userInfo;
            if(!$userInfo || !is_object($userInfo) || !$userInfo->id){
                $this->redirect(Url::to('/site/register'));
            } else {
                $this->goHome();
            }
        }

        $model = new LoginForm();

        if(Yii::$app->request->isPost){

            if ($model->login()) {
                return $this->redirect(Url::to('/site/register'));
            } else if(Yii::$app->request->post('mobile')) {
                $model->mobile = Yii::$app->request->post('mobile');
            }
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }


    public function actionRegister(){

        if (!is_null(Yii::$app->user->identity->userInfo))
            return $this->redirect(Url::to('/'));

        $this->layout = false;
        $model = new RegisterUserInfoModel();

        $model->clockTime = '09:30';
        $model->offDutyTime = '17:30';
        $model->sex = 1;
        $model->role = 1;
        $model->mobile = Yii::$app->user->identity->mobile;


        if(Yii::$app->request->isPost){
            if($model->create(Yii::$app->request->post())){
                $this->redirect(Url::to('/site/login'));
            } else {
            }
        }

        $currentAddInfo = MapHelper::getCurrentInfo();
//        print_r($currentAddInfo);exit;
        $currentAddExist = false;


        if(is_array($currentAddInfo) && count($currentAddInfo) && key_exists('status', $currentAddInfo) && $currentAddInfo['status']==0 ){
            if(key_exists('content', $currentAddInfo)) {
                $content = $currentAddInfo['content'];
                if(is_array($content) && key_exists('address', $content)) {
                    $currentAddExist = true;
                    $currentAddInfo['point'] = $content['point']['x'] . ',' . $content['point']['y'];
                }
            }
        }


        return $this->render('register', [
            'model' => $model,
            'currentAddInfo' => $currentAddInfo,
            'currentAddExist' => $currentAddExist
        ]);
    }

    public function actionRouteInfo(){

        $teamId = \Yii::$app->request->get('id');
        $teamModel = TeamModel::findOne(['team_id' => $teamId]);

        return $this->render('route_info', ['teamModel' => $teamModel]);

    }
    public function actionRouteList(){

        $teamList = TeamModel::find()->where(['>', 'team_id', 0])->all();
        return $this->render('teamList', ['teamList' => $teamList]);
    }

    public function actionRentCar(){
        return $this->render('rentCar');
    }

    public function actionRentCarInfo(){
        return $this->render('rentCarInfo');
    }

    public function actionRentCarType(){
        return $this->render('rentCarType');
    }

    public function actionTest(){


//        var_dump($user->open_id);
//        $info = $user->getWeChatInfo();
//
//        print_r($info);
//        $info = ArrayHelper::toArray($info);
//        $info['user_id'] = Yii::$app->user->identity->getId();
//
//        $weChatModel = new WeChatModel();
//        $rs = $weChatModel->createOrEdit($info);
//        var_dump($rs);
        exit;


        $info = MapHelper::getCurrentInfo();
        print_r($info);
        exit;

        $ip = file_get_contents("http://int.dpool.sina.com.cn/iplookup/iplookup.php?format=js");
        // 如果还要二次处理的话那么
        $ip = preg_replace('/[^/{]+(/{[^;]+);/i', '//1', $ip);

        $data = array();
        foreach(json_decode($ip, true) as $k => $v) {
            if($k == 'country') {
                $v = iconv('gb2312', 'utf-8', '你在').$v;
            }
            $data[$k] = $v;
        }

        $ip = 'var arr = ' . json_encode($data);
        print_r($ip);
        print_r($data);
        exit;

        return $this->render('route_info');
       /* $teamModel = new TeamModel();
        $driverId = 105;
        $passengerId = 107;
        $driver = UserIdentity::findOne(['id' => $driverId]);
        $passenger = UserIdentity::findOne(['id' => $passengerId]);
        $rs = $teamModel->create($driver, $passenger);*/
    }

    public function actionMyInfo(){

        $this->checkLogin();

        $userInfoModel = RegisterUserInfoModel::findOne(['user_id' => Yii::$app->user->identity->getId()]);
        if(!$userInfoModel)
            return $this->redirect(Url::to(['/site/register']));

        return $this->render('myInfo', [
            'model' => $userInfoModel
        ]);
    }
}
