<?php

namespace app\controllers;

use app\models\RegisterModel;
use app\models\RegisterUserInfoModel;
use app\models\TeamModel;
use app\models\TeamUserModel;
use app\models\UserIdentity;
use Yii;
use yii\filters\AccessControl;
use yii\helpers\Url;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

class SiteController extends BaseController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->layout = false;
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
//                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $teamModel = null;
        if(!Yii::$app->user->isGuest) {

            $userId = Yii::$app->user->identity->getId();

            $teamIds = TeamUserModel::find()->where(['user_id' => $userId])->select('team_id')->one() ;
            $teamModel = TeamModel::findOne([  'team_id' => $teamIds]);
        }

        return $this->render('index', [
            'teamModel' => $teamModel
        ]);
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {

            $user = UserIdentity::findOne(['id' => Yii::$app->user->id]);
            $userInfo = $user->userInfo;
            if(!$userInfo || !is_object($userInfo) || !$userInfo->id){
                $this->redirect(Url::to('/site/register'));
            } else {
                $this->goHome();
            }
        }

        $model = new LoginForm();

        if(Yii::$app->request->isPost){

            if ($model->login()) {
                return $this->redirect(Url::to('/site/register'));
            } else if(Yii::$app->request->post('mobile')) {
                $model->mobile = Yii::$app->request->post('mobile');
            }
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }


    public function actionRegister(){

        if (!is_null(Yii::$app->user->identity->userInfo))
            return $this->redirect(Url::to('/'));

        $this->layout = false;
        $model = new RegisterUserInfoModel();

        $model->clockTime = '09:30';
        $model->offDutyTime = '17:30';
        $model->sex = 1;
        $model->role = 1;
        $model->mobile = Yii::$app->user->identity->mobile;


        if(Yii::$app->request->isPost){
            if($model->create(Yii::$app->request->post())){
                $this->redirect(Url::to('/site/login'));
            } else {
            }
        }

        return $this->render('register', [
            'model' => $model
        ]);
    }

    public function actionRouteInfo(){

        $teamId = \Yii::$app->request->get('id');
        $teamModel = TeamModel::findOne(['team_id' => $teamId]);

        return $this->render('route_info', ['teamModel' => $teamModel]);

    }
    public function actionRouteList(){

        $teamList = TeamModel::find()->where(['>', 'team_id', 0])->all();
        return $this->render('teamList', ['teamList' => $teamList]);
    }

    public function actionRentCar(){
        return $this->render('rentCar');
    }

    public function actionRentCarInfo(){
        return $this->render('rentCarInfo');
    }

    public function actionRentCarType(){
        return $this->render('rentCarType');
    }

    public function actionTest(){

        return $this->render('route_info');
       /* $teamModel = new TeamModel();
        $driverId = 105;
        $passengerId = 107;
        $driver = UserIdentity::findOne(['id' => $driverId]);
        $passenger = UserIdentity::findOne(['id' => $passengerId]);
        $rs = $teamModel->create($driver, $passenger);*/
    }
}
