<?php
/**
 * Created by PhpStorm.
 * User: xiaohongyang
 * Date: 2016/11/29
 * Time: 20:39
 */

namespace app\models;


use phpDocumentor\Reflection\Types\Boolean;
use yii\base\Exception;
use yii\base\InvalidCallException;
use yii\behaviors\TimestampBehavior;
use yii\log\Logger;

class TeamModel extends BaseModel
{
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className()
            ]
        ];
    }


    public static function tableName()
    {
        return \Yii::$app->db->tablePrefix . 'team';
    }

    public function getTeamUsers(){
        return $this->hasMany(TeamUserModel::className(), ['team_id' => 'team_id']);
    }

    /**
     * 组成员用户collection
     * @return $this
     */
    public function getUsers(){
        return $this->hasMany(UserModel::className(), [ 'id' => 'user_id' ])
            ->via('teamUsers');
    }

    /**
     * 组添加乘客/司机(司机只在创建的时候添加)
     * @param UserModel $user
     * @return bool
     */
    public function addUser(UserModel $user) {
        $result = false;
        if($user->is_matched) {
            $this->message = "用户已经匹配过,不能重复匹配";
        } else if($this->family_number == self::CONT_MAX_FAMILY_NUMBER){
            $this->message = "通勤小组人数已满";
        } else {
            $result = $this->_addUser($user);
        }
        return $result;
    }

    /**
     * 组添加乘客/司机(司机只在创建的时候添加)
     * @param UserModel $user
     * @return bool
     */
    private function _addUser(UserModel $user){

        $rs = false;
        $transaction = $this->getConnection()->beginTransaction();
        try {
            $this->link('users', $user);
            //用户数加1
            $this->family_number += 1;
            $rs = $this->save();
            $user->updateIsMatched(true);
            $rs && $transaction->commit();
            $info = sprintf("组(%s)添加成员(%s)当前成员数(%s)", $this->team_id, $user->id, $this->family_number);
            \Yii::getLogger()->log($info, Logger::LEVEL_INFO);
        } catch (InvalidCallException $e) {
            \Yii::getLogger()->log($e->getMessage(), Logger::LEVEL_ERROR);
            $transaction->rollBack();
        } catch (Exception $e) {
            \Yii::getLogger()->log($e->getMessage(), Logger::LEVEL_ERROR);
            $transaction->rollBack();
        }
        return $rs;
    }

    /**
     * 创建组
     * @param UserModel $driver 司机
     * @param UserModel $passenger 乘客
     * @return bool 创建成功返回 true 或者 false
     * @throws \Exception
     */
    public function create(UserModel $driver, UserModel $passenger) {

        $rs = false;
        if($driver->id != $passenger->id){

            $transaction = $this->getConnection()->beginTransaction();

            try {
                if (!is_null($driver->userInfo) && $driver->userInfo->role != self::ROLE_DRIVER) {

                    $this->message = "用户不是司机";
                } else if (!$driver->is_matched && !$passenger->is_matched) {

                    //创建组
                    $team = new TeamModel();
                    $team->family_number = 0;
                    $team->driver_user_id = $driver->id;
                    $rsCreateTeam = $team->save();
                    //添加司机
                    $rsAddDriver = $team->addUser($driver);
                    //添加乘客
                    $rsAddPassenger = $team->addUser($passenger);
                    $rs = $rsCreateTeam && $rsAddDriver && $rsAddPassenger;
                }
                if($rs)
                    $transaction->commit();

            } catch (Exception $e) {
                $transaction->rollBack();
                \Yii::getLogger()->log($e->getMessage(), Logger::LEVEL_ERROR);
                throw $e;
            }
        } else {
            \Yii::getLogger()->log("自己不能和自己进行匹配建组!". $passenger->id, Logger::LEVEL_INFO);
        }
        return $rs;
    }

    /**
     * 组司机
     * @return null|\yii\db\ActiveQuery
     */
    public function getDriver() {

        return !$this->driver_user_id ?  null : $this->hasOne(UserModel::className(), [
            ['id' => 'driver_user_id']
        ]);
    }

    /**
     * 更新组信息前,判断成员数是超额
     * @param bool $insert
     * @return bool
     * @throws Exception
     */
    public function beforeSave($insert)
    {
        if (!$insert && $this->family_number > 4){

            \Yii::getLogger()->log("family_number 不能大于" . self::CONT_MAX_FAMILY_NUMBER);
            throw new Exception("family_number 不能大于" . self::CONT_MAX_FAMILY_NUMBER);
            return false;
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }


}